# LST_NRCELLALGOSWITCH = ['NR小区标识', 'NSA DC开关',
#                         'EPS FB开关', 'VoNR/EPS FB自适应开关', 'EPS FB最强邻区重定向开关', 'EPS FB提前下发测量开关',
#                         'EPS FB快速重定向开关', 'Voice Fallback指示开关', '基于VoNR语音质量的E-UTRAN切换开关', '基于VoNR和MCPTT语音质量的异频切换开关',
#                         'EPS FB E-UTRAN RSRP预测开关', 'VoNR退出gap测量开关', 'EPS FB目标小区选择开关', '语音基于上行覆盖切换开关',
#                         '连接态的VoNR/EPS FB自适应开关', '语音盲重定向频点选择开关',
#                         '移动至E-UTRAN开关', 'NSA与SA优选RSRP预测开关', '基于上行SINR移动至EUTRAN开关',
#                         'NR_NR邻区自配置开关', 'NR_EUTRAN邻区自配置开关', 'NR_NR邻区自删除开关', 'NR_EUTRAN邻区自删除开关', 'NR_NR邻区自动禁止切换开关',
#                         'NR_EUTRAN邻区自动禁止切换开关', 'PCI碰撞检测开关', 'PCI混淆检测开关', 'NR_NR超远邻区检测开关', 'NR_NR快速ANR开关',
#                         'NR_EUTRAN快速ANR开关', '自动NR频点关系开关', '自动EUTRAN频点关系开关', 'E-UTRAN PCI混淆检测开关',
#                         'NR_EUTRAN超远邻区检测开关',
#                         '特定PCI的NR邻区自配置开关', '基于系统内ANR的PCI冲突检测开关', '扩展邻区和多载波兼容开关',
#                         '基于覆盖的异频切换开关', '基于频率优先级的异频切换开关', '异频重定向开关', '基于运营商专用优先级的异频切换开关', '音视频异频切换配合开关',
#                         '基于业务的异频切换开关',
#                         '基于覆盖的异频盲切换开关', 'FR1到FR2频点轮询选择开关', '基于上行干扰的异频切换开关', '基于SSB SINR的异频切换开关', 'NSA基于上行干扰的异频切换开关',
#                         '异频切换配合开关', '基于能效的异频切换开关', '基于MBS兴趣指示的异频切换开关',
#                         'VoNR特性开关', '上行时延覆盖优化开关', '接入网比特率推荐开关', '上行RB预留开关', '基于邻区VoNR能力切换开关', '上行语音静音恢复开关',
#                         'ROHC头压缩开关', 'ROHC头解压失败恢复开关', '弱覆盖ROHC头压缩开关',
#                         '子协议0x0001', '子协议0x0002', '上行子协议0x0006',
#                         'RRC快速释放开关', '终端释放偏好开关', 'DRX偏好配置功能开关',
#                         'RRC INACTIVE开关', 'RedCap RRC INACTIVE开关', 'RedCap RRC INACTIVE RA-SDT开关',
#                         'SSB测量位置策略开关', '室内外交叠区测量开关',
#                         '异频连接态MLB开关', '异频空闲态MLB开关',
#                         'NR到E-UTRAN频点列表控制开关', '异频频点列表控制开关', '基于RFSP返回HPLMN的异频切换开关', '基于频率优先级切换开关', '频点测量配置更新开关',
#                         '上行视频直播特性增强开关', '上行PDCP流量整形开关', 'NSA上行PDCP流量整形开关',
#                         '基于网络切片标识的准入开关', '网络切片增强开关',
#                         'CloudX业务开关', 'CloudX业务DAPS增强开关', 'CloudX帧识别开关',
#                         'E-CID定位开关', 'UTDOA定位测量开关', 'SRS RSRP定位测量开关', 'AOA+UTDOA融合定位开关', '多小区SRS测量开关',
#                         'Redcap低功耗高精度定位开关',
#                         '站间切换全量配置开关', '协议信元优化开关', '小区内切换UE上下文建立流程开关', '站间PLMN保留切换开关', '切换入不伴随SUL开关',
#                         '非资源类E-UTRAN切换惩罚开关', '非资源类NR系统内切换惩罚开关', '基于测量报告重定向开关',
#                         '过热辅助信息处理开关', '终端删除SUL开关', '终端降CC开关', '终端降MIMO层数开关', '终端去激活SCC开关', 'RedCap用户DRX偏好配置上报开关',
#                         '终端降带宽开关', 'NSA场景UAI功能开关',
#                         '高速差异化调度开关', '高速定向切换开关', '低速性能优化开关', '高速小区公专网干扰协同开关', '低速UE DRX开关', '高速用户重定向开关',
#                         '低速差异化EPS FALLBACK开关', '干扰协同固定生效开关', '高速波束避让开关', '干扰邻区识别开关',
#                         'ROHC模式', '加速用户保障开关', '基于RRC建立原因的准入开关',
#                         'RRC重配消息传输优化开关', 'A2盲重定向控制开关', '差异化接入流程优化开关',
#                         '重配消息传输间隔(毫秒)', '以太网类型PDU会话开关',
#                         '用户数抢占开关', '拒绝等待时长开关',
#                         '高精度授时开关', '业务量识别开关', 'MCX开关',
#                         '基于覆盖的异频切换测量量预测开关', '基于业务的异频切换测量量预测开关', '基于上行干扰的异频切换测量量预测开关', '基于频率优先级的异频切换测量量预测开关',
#                         'FR1到FR2的NR-DC开关',
#                         '多频智选开关', '下行体验评估频谱效率预测开关', '上行弱覆盖用户保护开关', '多频波束协同下行频谱效率预测开关', '载波添加测量量预测开关', '干扰隔离开关',
#                         '基于能效的协同调度开关', '多频智选预测开关',
#                         '异频邻区上行干扰信息开关',
#                         '基于信道质量切换开关', '同频条件切换开关', '同频协同切换优化开关',
#                         '多频智选模式',
#                         '基于覆盖的同频切换开关',
#                         '同频协同切换模式']
import configuration
EMPTY_VALUE = "NULL"
END = "END"
QUERY = "查询"
RETURN_CODE = "RETCODE"
COMMAND = "命令"
MESSAGE = "报文"
HUAWEI_COLS_ORDER = [
    '地市',
    '网元',
    'NR小区标识',
    'NRDU小区名称',
    'CGI',
    '频带',
    '双工模式',
    '覆盖类型',
    '覆盖场景',
    '厂家',
    '服务质量等级',
    '基于覆盖的异频A1RSRP触发门限(dBm)',
    '基于覆盖的异频A2RSRP触发门限(dBm)',
    '基于覆盖的异频A5RSRP触发门限1(dBm)',
    '基于覆盖的异频A5RSRP触发门限2(dBm)',
    '异系统切换A1RSRP门限(dBm)',
    '异系统切换A2RSRP门限(dBm)',
    '异系统切换触发事件类型',
    '基于覆盖的切换至E-UTRANB2RSRP门限1(dBm)',
    '基于覆盖的切换B1RSRP门限(dBm)',
    '基于频率优先级的异频切换开关',
    '基于频率优先级的异频切换A1RSRP门限(dBm)',
    '基于频率优先级的异频切换A4RSRP门限(dBm)',
    '基于上行SINR移动至EUTRAN开关',
    # '基于上行SINR移动至EUTRAN开关',
    'NR迁移到E-UTRAN的上行SINR低门限(0.1dB)',
    '基于上行SINR的切换至E-UTRANB2RSRP门限1(dBm)',
    '网络架构优选的RSRP触发门限(dBm)'
]


HUAWEI_DEMAND_PARAMS = [
    '基于覆盖的异频A1RSRP触发门限(dBm)',
    '基于覆盖的异频A2RSRP触发门限(dBm)',
    '基于覆盖的异频A5RSRP触发门限1(dBm)',
    '基于覆盖的异频A5RSRP触发门限2(dBm)',
    '异系统切换A1RSRP门限(dBm)',
    '异系统切换A2RSRP门限(dBm)',
    '异系统切换触发事件类型',
    '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
    '基于覆盖的切换B1RSRP门限(dBm)',
    '基于频率优先级的异频切换开关',
    '基于频率优先级的异频切换A1RSRP门限(dBm)',
    '基于频率优先级的异频切换A4RSRP门限(dBm)',
    '基于上行SINR移动至EUTRAN开关:移动至E-UTRAN开关&基于上行SINR移动至EUTRAN开关',
    # '基于上行SINR移动至EUTRAN开关',
    'NR迁移到E-UTRAN的上行SINR低门限(0.1dB)',
    '基于上行SINR的切换至E-UTRANB2RSRP门限1(dBm)',
    '网络架构优选的RSRP触发门限(dBm)'
]
LST_NRCELLALGOSWITCH = ['网元', 'NR小区标识', 'NSA DC开关', '语音策略开关', ' 系统间业务移动性算法开关', ' 邻区自配置开关',
                        ' 异频切换算法开关', ' VoNR开关', ' ROHC头压缩开关', ' ROHC子协议开关', ' 终端节能开关',
                        ' INACTIVE策略开关', '测量策略开关', '负载均衡算法开关', ' 基于RFSP的算法开关', ' 视频直播开关',
                        '网络切片算法开关', ' CloudX业务开关', ' 定位业务开关', ' 切换兼容性开关', ' 终端辅助信息处理开关',
                        '高速专属策略开关', ' ROHC模式', '加速开关', ' FWA算法开关', ' 流程开关', '重配消息传输间隔(毫秒)',
                        '面向企业客户的业务开关', '无线准入控制算法开关', ' 业务功能开关', '异频切换AI优化开关', ' NR-DC开关',
                        ' 多频算法开关', ' 邻区信息控制开关', ' 同频切换算法开关', ' 多频智选模式', '同频切换开关', '同频协同切换模式']

LST_GNODEBFUNCTION = ['网元', 'gNodeB功能名称', '引用的应用标识', 'gNodeB标识', 'gNodeB标识长度(比特)', '用户标签', '网元资源模型版本', '产品版本']

LST_NRDUCELL = ['网元', 'NR DU小区标识', 'NR DU小区名称', '双工模式', '小区标识', '物理小区标识', '频带', '上行频点', '下行频点',
                '上行带宽', '下行带宽', '小区半径(米)', '子载波间隔(KHz)', '循环前缀长度', '时隙配比', '时隙结构', 'RAN通知区域标识',
                'LampSite小区标识', '跟踪区域标识',
                'TA偏移量', '小区管理状态', 'SSB频域位置描述方式', 'SSB频域位置', 'SSB周期(毫秒)', 'SIB1周期(毫秒)',
                'NR DU小区组网模式', '系统消息配置标识', '根序列逻辑索引', 'PRACH频域起始位置', '高速小区标识', '辅助小区指示',
                'SMTC持续时间(毫秒)', 'SMTC周期(毫秒)', '附加频带', 'SSB子载波间隔(KHz)', '客户化带宽配置标识', '客户化下行带宽',
                '客户化上行带宽', '上行闭塞RB个数偏置', '对端时隙配比', 'SSB时域位置', '小区禁止状态',
                '部署位置', 'IAB节点标识']
LST_NRCELLINTERFHOMEAGRP_INTERFREQHOMEASGROUPID_0 = ['网元', 'NR小区标识', '异频切换测量参数组标识', '异频测量事件时间迟滞(毫秒)',
                                                     '异频测量事件幅度迟滞(0.5dB)',
                                                     '异频A1A2时间迟滞(毫秒)', '异频A1A2幅度迟滞(0.5dB)',
                                                     '基于频率优先级的异频切换A2 RSRP门限(dBm)', '基于频率优先级的异频切换A1 RSRP门限(dBm)',
                                                     '基于覆盖的异频A5 RSRP触发门限1(dBm)', '基于覆盖的异频A5 RSRP触发门限2(dBm)',
                                                     '基于覆盖的异频A2 RSRP触发门限(dBm)', '基于覆盖的异频A1 RSRP触发门限(dBm)',
                                                     '基于频率优先级的异频切换A4 RSRP门限(dBm)',
                                                     '基于MLB的异频A4 RSRP门限(dBm)', '运营商专用优先级异频切换A4 RSRP门限(dBm)',
                                                     '基于业务的异频切换A4 RSRP门限(dBm)', '基于覆盖的异频RSRQ门限(0.5dB)',
                                                     '基于覆盖的异频A2 RSRQ触发门限(0.5dB)', '基于覆盖的异频A1 RSRQ触发门限(0.5dB)',
                                                     '基于干扰的异频切换A3 RSRP偏置(0.5dB)', '基于干扰的异频切换RSRP门限(dBm)',
                                                     '基于SSB SINR的异频切换A1门限(0.5dB)', '基于SSB SINR的异频切换A2门限(0.5dB)',
                                                     '基于A3异频切换的A2 RSRP触发门限(dBm)', '基于A3异频切换的A1 RSRP触发门限(dBm)',
                                                     '异频切换A3偏置(0.5dB)', '基于上行覆盖的异频A5 RSRP触发门限1(dBm)',
                                                     '高速用户A2门限偏置(dB)', '基于MBS兴趣指示的异频切换A5 RSRP触发门限2(dBm)',
                                                     '基于覆盖的异频切换A5 SINR门限2(0.5dB)', '异频盲重定向A2 SINR门限(0.5dB)',
                                                     '特殊终端基于频率优先级切换的A1 RSRP门限(dBm)', '特殊终端基于频率优先级切换的A2 RSRP门限(dBm)',
                                                     '特殊终端基于频率优先级切换的A4 RSRP门限(dBm)', '基于干扰隔离的异频A5 RSRP触发门限1(dBm)']
LST_NRINTERRATHOPARAM = ['网元', 'NR小区标识',
                         '切换方式开关',
                         'EPS FB保护定时器(100毫秒)', '异系统切换触发事件类型', 'EPS FB模式', 'EPS FB测量保护定时器(100毫秒)', '下行资源比',
                         'EPS FB等待多频点B1测量报告定时器时长(10毫秒)']
LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_0 = ['网元','NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
                                                    '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
                                                    '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
                                                    '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
                                                    'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
                                                    '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
                                                    '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
                                                    '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_1 = ['网元', 'NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
                                                    '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
                                                    '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
                                                    '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
                                                    'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
                                                    '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
                                                    '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
                                                    '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_2 = ['网元', 'NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
                                                    '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
                                                    '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
                                                    '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
                                                    'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
                                                    '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
                                                    '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
                                                    '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_0 = ['网元', 'NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
                                                        '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
                                                        'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
                                                        'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
                                                        '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
                                                        'EPSFB B1 RSRQ门限(0.5dB)']
LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_1 = ['网元', 'NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
                                                        '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
                                                        'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
                                                        'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
                                                        '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
                                                        'EPSFB B1 RSRQ门限(0.5dB)']
LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_2 = ['网元', 'NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
                                                        '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
                                                        'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
                                                        'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
                                                        '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
                                                        'EPSFB B1 RSRQ门限(0.5dB)']
# LST_NRDUCELLSRSMEAS = ['NR DU小区标识', 'NSA TDM功控触发SINR幅度迟滞(0.1dB)', 'NSA TDM功控触发SINR门限(0.1dB)', 'SRS TA测量开关',
#                        ' NSA 上行回落到LTE SINR迟滞(0.1dB)', 'NSA 上行回落到LTE SINR门限(0.1dB)',
#                        'Hyper Cell内TRP间切换的RSRP差值(0.5dB)', 'NSA上行路径选择SINR高门限(0.1dB)', 'NSA上行路径选择SINR低门限(0.1dB)',
#                        'NSA分流用户上行路径选择SINR门限(0.1dB)', 'NSA上行路径选择SINR幅度迟滞(0.1dB)', 'NSA上行路径选择SINR时间迟滞(100毫秒)',
#                        'NSA上行路径变更至LTE速率比', 'NSA上行路径变更至NR速率比', 'NSA上行小包返回NR后惩罚时长(秒)', 'NSA 上行回落到LTE SINR时间迟滞(100毫秒)',
#                        'NSA上行回落到LTE SINR优化开关', 'UL ROHC的SINR门限(0.1dB)', 'UL ROHC的SINR幅度迟滞(0.1dB)',
#                        'DMM TRP选择RSRP差值门限(dB)', '上行SRS测量值使用开关', 'SRS干扰门限(dB)', 'NR迁移到E-UTRAN的上行SINR低门限(0.1dB)',
#                        'E-UTRAN迁移到NR的SINR高门限(0.1dB)', 'SRS TA异常保护门限(Ts)', 'SRS均衡前信干噪比低门限(0.2dB)', 'SRS测量优化策略',
#                        ' SRS RSRP异常门限(dB)', 'DMRS TA的SINR判决门限(dB)', 'SRS和DMRS TA差值门限(Ts)', 'SRS测量扩展开关',
#                        ' SRS干扰下TA测量优化开关']
LST_NRDUCELLSRSMEAS = ['网元', 'NR DU小区标识', 'NSA TDM功控触发SINR幅度迟滞(0.1dB)',
                       'NSA TDM功控触发SINR门限(0.1dB)', 'SRS TA测量开关',
                       ' NSA 上行回落到LTE SINR迟滞(0.1dB)', 'NSA 上行回落到LTE SINR门限(0.1dB)',
                       'Hyper Cell内TRP间切换的RSRP差值(0.5dB)', 'NSA上行路径选择SINR高门限(0.1dB)',
                       'NSA上行路径选择SINR低门限(0.1dB)', 'NSA分流用户上行路径选择SINR门限(0.1dB)',
                       'NSA上行路径选择SINR幅度迟滞(0.1dB)', 'NSA上行路径选择SINR时间迟滞(100毫秒)',
                       'NSA上行路径变更至LTE速率比', 'NSA上行路径变更至NR速率比', 'NSA上行小包返回NR后惩罚时长(秒)',
                       'NSA 上行回落到LTE SINR时间迟滞(100毫秒)', 'NSA上行回落到LTE SINR优化开关',
                       'UL ROHC的SINR门限(0.1dB)', 'UL ROHC的SINR幅度迟滞(0.1dB)',
                       'DMM TRP选择RSRP差值门限(dB)', '上行SRS测量值使用开关', 'SRS干扰门限(dB)',
                       'NR迁移到E-UTRAN的上行SINR低门限(0.1dB)', 'E-UTRAN迁移到NR的SINR高门限(0.1dB)',
                       'SRS TA异常保护门限(Ts)', 'SRS均衡前信干噪比低门限(0.2dB)', 'SRS测量优化策略',
                       ' SRS RSRP异常门限(dB)', 'DMRS TA的SINR判决门限(dB)', 'SRS和DMRS TA差值门限(Ts)',
                       'SRS测量扩展开关', ' SRS干扰下TA测量优化开关', 'SRS测量优化开关']

LST_NRCELLQCIBEARER_QCI_1 = ['网元', 'NR小区标识', '服务质量等级', '流控参数组标识', 'AM模式PDCP参数组标识', 'UM模式PDCP参数组标识',
                             'RLC模式', 'DRX参数组标识', '异系统切换测量参数组标识', '异系统切换至E-UTRAN测量参数组标识',
                             '同频切换测量参数组标识', '异频切换测量参数组标识', 'NSA DC配置参数组标识',
                             '切换与QoS流程冲突处理策略', '负载均衡算法开关', ' 负载均衡的下行吞吐率门限(千比特/秒)',
                             '负载均衡的上行吞吐率门限(千比特/秒)', '负载均衡的下行缓存数据量(千比特)',
                             '负载均衡的上行BSR数据量(千比特)', '负载均衡的检查时长(秒)', 'NSA用户异频切换测量参数组标识',
                             '低速用户同频切换测量参数组标识', '低速用户异频切换测量参数组标识', 'RedCap用户DRX参数组标识',
                             '业务释放延迟定时器(毫秒)', 'gNodeB频点优先级组标识', 'QCI算法参数组标识']

LST_NRCELLQCIBEARER_QCI_5 = ['网元', 'NR小区标识', '服务质量等级', '流控参数组标识', 'AM模式PDCP参数组标识',
                             'UM模式PDCP参数组标识', 'RLC模式', 'DRX参数组标识', '异系统切换测量参数组标识',
                             '异系统切换至E-UTRAN测量参数组标识', '同频切换测量参数组标识', '异频切换测量参数组标识',
                             'NSA DC配置参数组标识', '切换与QoS流程冲突处理策略', '负载均衡算法开关',
                             ' 负载均衡的下行吞吐率门限(千比特/秒)', '负载均衡的上行吞吐率门限(千比特/秒)',
                             '负载均衡的下行缓存数据量(千比特)', '负载均衡的上行BSR数据量(千比特)', '负载均衡的检查时长(秒)',
                             'NSA用户异频切换测量参数组标识', '低速用户同频切换测量参数组标识', '低速用户异频切换测量参数组标识',
                             'RedCap用户DRX参数组标识', '业务释放延迟定时器(毫秒)', 'gNodeB频点优先级组标识',
                             'QCI算法参数组标识']
LST_NRCELLQCIBEARER_QCI_9 = ['网元', 'NR小区标识', '服务质量等级', '流控参数组标识', 'AM模式PDCP参数组标识',
                             'UM模式PDCP参数组标识', 'RLC模式', 'DRX参数组标识', '异系统切换测量参数组标识',
                             '异系统切换至E-UTRAN测量参数组标识', '同频切换测量参数组标识', '异频切换测量参数组标识',
                             'NSA DC配置参数组标识', '切换与QoS流程冲突处理策略', '负载均衡算法开关',
                             ' 负载均衡的下行吞吐率门限(千比特/秒)', '负载均衡的上行吞吐率门限(千比特/秒)',
                             '负载均衡的下行缓存数据量(千比特)', '负载均衡的上行BSR数据量(千比特)', '负载均衡的检查时长(秒)',
                             'NSA用户异频切换测量参数组标识', '低速用户同频切换测量参数组标识', '低速用户异频切换测量参数组标识',
                             'RedCap用户DRX参数组标识', '业务释放延迟定时器(毫秒)', 'gNodeB频点优先级组标识',
                             'QCI算法参数组标识']
COMMAND_LIST = [LST_NRDUCELL, LST_GNODEBFUNCTION, LST_NRCELLALGOSWITCH,
                LST_NRCELLINTERFHOMEAGRP_INTERFREQHOMEASGROUPID_0,
                LST_NRINTERRATHOPARAM, LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_0,
                LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_1,
                LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_2,
                LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_0,
                LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_1,
                LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_2,
                LST_NRDUCELLSRSMEAS,
                LST_NRCELLQCIBEARER_QCI_1, LST_NRCELLQCIBEARER_QCI_5, LST_NRCELLQCIBEARER_QCI_9]

COMMAND_NAME_LIST = ['LST NRDUCELL:;', 'LST GNODEBFUNCTION:;', 'LST NRCELLALGOSWITCH:;',
                     'LST NRCELLINTERFHOMEAGRP:INTERFREQHOMEASGROUPID=0;', 'LST NRINTERRATHOPARAM:;',
                     'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=0;',
                     'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=1;',
                     'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=2;',
                     'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=0;',
                     'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=1;',
                     'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=2;',
                     'LST NRDUCELLSRSMEAS:;',
                     'LST NRCELLQCIBEARER:QCI=1;',
                     'LST NRCELLQCIBEARER:QCI=5;',
                     'LST NRCELLQCIBEARER:QCI=9;']

# class HuaweiConfiguration:
#
#     def __init__(self):
#         self.command_content_dict = {}


# self.LST_NRCELLALGOSWITCH = ['NR小区标识', 'NSA DC开关',
#                         'EPS FB开关', 'EPS FB开关', 'VoNR/EPS FB自适应开关', 'EPS FB最强邻区重定向开关', 'EPS FB提前下发测量开关',
#                         'EPS FB快速重定向开关', 'Voice Fallback指示开关', '基于VoNR语音质量的E-UTRAN切换开关', '基于VoNR和MCPTT语音质量的异频切换开关',
#                         'EPS FB E-UTRAN RSRP预测开关', 'VoNR退出gap测量开关', 'EPS FB目标小区选择开关', '语音基于上行覆盖切换开关',
#                         '连接态的VoNR/EPS FB自适应开关', '语音盲重定向频点选择开关',
#                         '移动至E-UTRAN开关', 'NSA与SA优选RSRP预测开关', '基于上行SINR移动至EUTRAN开关',
#                         'NR_NR邻区自配置开关', 'NR_EUTRAN邻区自配置开关', 'NR_NR邻区自删除开关', 'NR_EUTRAN邻区自删除开关', 'NR_NR邻区自动禁止切换开关',
#                         'NR_EUTRAN邻区自动禁止切换开关', 'PCI碰撞检测开关', 'PCI混淆检测开关', 'NR_NR超远邻区检测开关', 'NR_NR快速ANR开关',
#                         'NR_EUTRAN快速ANR开关', '自动NR频点关系开关', '自动EUTRAN频点关系开关', 'E-UTRAN PCI混淆检测开关',
#                         'NR_EUTRAN超远邻区检测开关',
#                         '特定PCI的NR邻区自配置开关', '基于系统内ANR的PCI冲突检测开关', '扩展邻区和多载波兼容开关',
#                         '基于覆盖的异频切换开关', '基于频率优先级的异频切换开关', '异频重定向开关', '基于运营商专用优先级的异频切换开关', '音视频异频切换配合开关',
#                         '基于业务的异频切换开关',
#                         '基于覆盖的异频盲切换开关', 'FR1到FR2频点轮询选择开关', '基于上行干扰的异频切换开关', '基于SSB SINR的异频切换开关', 'NSA基于上行干扰的异频切换开关',
#                         '异频切换配合开关', '基于能效的异频切换开关', '基于MBS兴趣指示的异频切换开关',
#                         'VoNR特性开关', '上行时延覆盖优化开关', '接入网比特率推荐开关', '上行RB预留开关', '基于邻区VoNR能力切换开关', '上行语音静音恢复开关',
#                         'ROHC头压缩开关', 'ROHC头解压失败恢复开关', '弱覆盖ROHC头压缩开关',
#                         '子协议0x0001', '子协议0x0002', '上行子协议0x0006',
#                         'RRC快速释放开关', '终端释放偏好开关', 'DRX偏好配置功能开关',
#                         'RRC INACTIVE开关', 'RedCap RRC INACTIVE开关', 'RedCap RRC INACTIVE RA-SDT开关',
#                         'SSB测量位置策略开关', '室内外交叠区测量开关',
#                         '异频连接态MLB开关', '异频空闲态MLB开关',
#                         'NR到E-UTRAN频点列表控制开关', '异频频点列表控制开关', '基于RFSP返回HPLMN的异频切换开关', '基于频率优先级切换开关', '频点测量配置更新开关',
#                         '上行视频直播特性增强开关', '上行PDCP流量整形开关', 'NSA上行PDCP流量整形开关',
#                         '基于网络切片标识的准入开关', '网络切片增强开关',
#                         'CloudX业务开关', 'CloudX业务DAPS增强开关', 'CloudX帧识别开关',
#                         'E-CID定位开关', 'UTDOA定位测量开关', 'SRS RSRP定位测量开关', 'AOA+UTDOA融合定位开关', '多小区SRS测量开关',
#                         'Redcap低功耗高精度定位开关',
#                         '站间切换全量配置开关', '协议信元优化开关', '小区内切换UE上下文建立流程开关', '站间PLMN保留切换开关', '切换入不伴随SUL开关',
#                         '非资源类E-UTRAN切换惩罚开关', '非资源类NR系统内切换惩罚开关', '基于测量报告重定向开关',
#                         '过热辅助信息处理开关', '终端删除SUL开关', '终端降CC开关', '终端降MIMO层数开关', '终端去激活SCC开关', 'RedCap用户DRX偏好配置上报开关',
#                         '终端降带宽开关', 'NSA场景UAI功能开关',
#                         '高速差异化调度开关', '高速定向切换开关', '低速性能优化开关', '高速小区公专网干扰协同开关', '低速UE DRX开关', '高速用户重定向开关',
#                         '低速差异化EPS FALLBACK开关', '干扰协同固定生效开关', '高速波束避让开关', '干扰邻区识别开关',
#                         'ROHC模式', '加速用户保障开关', '基于RRC建立原因的准入开关',
#                         'RRC重配消息传输优化开关', 'A2盲重定向控制开关', '差异化接入流程优化开关',
#                         '重配消息传输间隔(毫秒)', '以太网类型PDU会话开关',
#                         '用户数抢占开关', '拒绝等待时长开关',
#                         '高精度授时开关', '业务量识别开关', 'MCX开关',
#                         '基于覆盖的异频切换测量量预测开关', '基于业务的异频切换测量量预测开关', '基于上行干扰的异频切换测量量预测开关', '基于频率优先级的异频切换测量量预测开关',
#                         'FR1到FR2的NR-DC开关',
#                         '多频智选开关', '下行体验评估频谱效率预测开关', '上行弱覆盖用户保护开关', '多频波束协同下行频谱效率预测开关', '载波添加测量量预测开关', '干扰隔离开关',
#                         '基于能效的协同调度开关', '多频智选预测开关',
#                         '异频邻区上行干扰信息开关',
#                         '基于信道质量切换开关', '同频条件切换开关', '同频协同切换优化开关',
#                         '多频智选模式',
#                         '基于覆盖的同频切换开关']
#
# self.LST_GNODEBFUNCTION = ['gNodeB功能名称', '引用的应用标识', 'gNodeB标识', 'gNodeB标识长度(比特)', '用户标签', '网元资源模型版本', '产品版本']
#
# self.LST_NRDUCELL = ['NR DU小区标识', 'NR DU小区名称', '双工模式', '小区标识', '物理小区标识', '频带', '上行频点', '下行频点',
#                 '上行带宽', '下行带宽', '小区半径(米)', '子载波间隔(KHz)', '循环前缀长度', '时隙配比', '时隙结构', 'RAN通知区域标识',
#                 'LampSite小区标识', '跟踪区域标识',
#                 'TA偏移量', '小区管理状态', 'SSB频域位置描述方式', 'SSB频域位置', 'SSB周期(毫秒)', 'SIB1周期(毫秒)',
#                 'NR DU小区组网模式', '系统消息配置标识', '根序列逻辑索引', 'PRACH频域起始位置', '高速小区标识', '辅助小区指示',
#                 'SMTC持续时间(毫秒)', 'SMTC周期(毫秒)', '附加频带', 'SSB子载波间隔(KHz)', '客户化带宽配置标识', '客户化下行带宽',
#                 '客户化上行带宽', '上行闭塞RB个数偏置', '对端时隙配比', 'SSB时域位置', '小区禁止状态',
#                 '部署位置', 'IAB节点标识']
# self.LST_NRCELLINTERFHOMEAGRP_INTERFREQHOMEASGROUPID_0 = ['NR小区标识', '异频切换测量参数组标识', '异频测量事件时间迟滞(毫秒)', '异频测量事件幅度迟滞(0.5dB)',
#                                                      '异频A1A2时间迟滞(毫秒)', '异频A1A2幅度迟滞(0.5dB)',
#                                                      '基于频率优先级的异频切换A2 RSRP门限(dBm)', '基于频率优先级的异频切换A1 RSRP门限(dBm)',
#                                                      '基于覆盖的异频A5 RSRP触发门限1(dBm)', '基于覆盖的异频A5 RSRP触发门限2(dBm)',
#                                                      '基于覆盖的异频A2 RSRP触发门限(dBm)', '基于覆盖的异频A1 RSRP触发门限(dBm)',
#                                                      '基于频率优先级的异频切换A4 RSRP门限(dBm)',
#                                                      '基于MLB的异频A4 RSRP门限(dBm)', '运营商专用优先级异频切换A4 RSRP门限(dBm)',
#                                                      '基于业务的异频切换A4 RSRP门限(dBm)', '基于覆盖的异频RSRQ门限(0.5dB)',
#                                                      '基于覆盖的异频A2 RSRQ触发门限(0.5dB)', '基于覆盖的异频A1 RSRQ触发门限(0.5dB)',
#                                                      '基于干扰的异频切换A3 RSRP偏置(0.5dB)', '基于干扰的异频切换RSRP门限(dBm)',
#                                                      '基于SSB SINR的异频切换A1门限(0.5dB)', '基于SSB SINR的异频切换A2门限(0.5dB)',
#                                                      '基于A3异频切换的A2 RSRP触发门限(dBm)', '基于A3异频切换的A1 RSRP触发门限(dBm)',
#                                                      '异频切换A3偏置(0.5dB)', '基于上行覆盖的异频A5 RSRP触发门限1(dBm)',
#                                                      '高速用户A2门限偏置(dB)', '基于MBS兴趣指示的异频切换A5 RSRP触发门限2(dBm)',
#                                                      '基于覆盖的异频切换A5 SINR门限2(0.5dB)', '异频盲重定向A2 SINR门限(0.5dB)']
# self.LST_NRINTERRATHOPARAM = ['NR小区标识',
#                          'E-UTRAN切换开关', 'E-UTRAN重定向开关', '语音业务盲模式开关', '基于覆盖的E-UTRAN最强邻区重定向开关', 'VoNR基于覆盖的切换优先开关',
#                          '重建流程中EPS Fallback变更开关',
#                          'EPS FB保护定时器(100毫秒)', '异系统切换触发事件类型', 'EPS FB模式', 'EPS FB测量保护定时器(100毫秒)', '下行资源比',
#                          'EPS FB等待多频点B1测量报告定时器时长(10毫秒)']
#
# self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_0 = ['NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
#                                                     '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
#                                                     '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
#                                                     '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
#                                                     'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
#                                                     '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
#                                                     '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
#                                                     '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
# self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_1 = ['NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
#                                                     '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
#                                                     '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
#                                                     '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
#                                                     'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
#                                                     '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
#                                                     '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
#                                                     '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
# self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_2 = ['NR小区标识', '异系统切换测量参数组标识', '异系统切换A1 RSRP门限(dBm)',
#                                                     '异系统切换A2 RSRP门限(dBm)', '异系统切换A1A2幅度迟滞(0.5dB)',
#                                                     '异系统切换A1A2时间迟滞(毫秒)', '基于覆盖的切换至E-UTRAN盲A2 RSRP门限(dBm)',
#                                                     '基于覆盖的切换至E-UTRAN B2 RSRP门限1(dBm)',
#                                                     'VoNR/EPS FB自适应A2 RSRP门限(dBm)', 'VoNR/EPS FB自适应A2事件时间迟滞(毫秒)',
#                                                     '异系统切换A2 RSRQ门限(0.5dB)', '异系统切换A1 RSRQ门限(0.5dB)',
#                                                     '基于覆盖的切换至E-UTRAN盲A2 RSRQ门限(0.5dB)',
#                                                     '基于上行SINR的切换至E-UTRAN B2 RSRP门限1(dBm)']
# self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_0 = ['NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
#                                                         '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
#                                                         'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
#                                                         'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
#                                                         '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
#                                                         'EPSFB B1 RSRQ门限(0.5dB)']
# self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_1 = ['NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
#                                                         '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
#                                                         'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
#                                                         'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
#                                                         '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
#                                                         'EPSFB B1 RSRQ门限(0.5dB)']
# self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_2 = ['NR小区标识', '异系统切换至E-UTRAN测量参数组标识', '基于覆盖的切换B1 RSRP门限(dBm)',
#                                                         '基于覆盖的切换B1B2幅度迟滞(0.5dB)', '基于覆盖的切换B1B2时间迟滞(毫秒)',
#                                                         'EPSFB B1 RSRP门限(dBm)', 'EPSFB B1幅度迟滞(0.5dB)',
#                                                         'EPSFB B1时间迟滞(毫秒)', 'LNR载波关断B1 RSRP门限(dBm)',
#                                                         '网络架构优选的RSRP触发门限(dBm)', '基于覆盖的切换B1 RSRQ门限(0.5dB)',
#                                                         'EPSFB B1 RSRQ门限(0.5dB)']
# self.LST_NRDUCELLSRSMEAS = ['NR DU小区标识', 'NSA TDM功控触发SINR幅度迟滞(0.1dB)', 'NSA TDM功控触发SINR门限(0.1dB)', 'SRS TA测量开关',
#                        ' NSA 上行回落到LTE SINR迟滞(0.1dB)', 'NSA 上行回落到LTE SINR门限(0.1dB)',
#                        'Hyper Cell内TRP间切换的RSRP差值(0.5dB)', 'NSA上行路径选择SINR高门限(0.1dB)', 'NSA上行路径选择SINR低门限(0.1dB)',
#                        'NSA分流用户上行路径选择SINR门限(0.1dB)', 'NSA上行路径选择SINR幅度迟滞(0.1dB)', 'NSA上行路径选择SINR时间迟滞(100毫秒)',
#                        'NSA上行路径变更至LTE速率比', 'NSA上行路径变更至NR速率比', 'NSA上行小包返回NR后惩罚时长(秒)', 'NSA 上行回落到LTE SINR时间迟滞(100毫秒)',
#                        'NSA上行回落到LTE SINR优化开关', 'UL ROHC的SINR门限(0.1dB)', 'UL ROHC的SINR幅度迟滞(0.1dB)',
#                        'DMM TRP选择RSRP差值门限(dB)', '上行SRS测量值使用开关', 'SRS干扰门限(dB)', 'NR迁移到E-UTRAN的上行SINR低门限(0.1dB)',
#                        'E-UTRAN迁移到NR的SINR高门限(0.1dB)', 'SRS TA异常保护门限(Ts)', 'SRS均衡前信干噪比低门限(0.2dB)', 'SRS测量优化策略',
#                        ' SRS RSRP异常门限(dB)', 'DMRS TA的SINR判决门限(dB)', 'SRS和DMRS TA差值门限(Ts)', 'SRS测量扩展开关',
#                        ' SRS干扰下TA测量优化开关']
# self.COMMAND_LIST = [self.LST_NRDUCELL, self.LST_GNODEBFUNCTION, self.LST_NRCELLALGOSWITCH,
#                 self.LST_NRCELLINTERFHOMEAGRP_INTERFREQHOMEASGROUPID_0,
#                 self.LST_NRINTERRATHOPARAM, self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_0,
#                 self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_1,
#                 self.LST_NRCELLINTERRHOMEAGRP_INTERRATHOMEASGROUPID_2,
#                 self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_0,
#                 self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_1,
#                 self.LST_NRCELLHOEUTRANMEAGRP_INTERRHOTOEUTRANMEASGRPID_2, self.LST_NRDUCELLSRSMEAS]
# self.COMMAND_NAME_LIST = ['LST NRDUCELL', 'LST GNODEBFUNCTION', 'LST NRCELLALGOSWITCH',
#                      'LST NRCELLINTERFHOMEAGRP:INTERFREQHOMEASGROUPID=0', 'LST NRINTERRATHOPARAM',
#                      'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=0',
#                      'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=1',
#                      'LST NRCELLINTERRHOMEAGRP:INTERRATHOMEASGROUPID=2',
#                      'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=0',
#                      'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=1',
#                      'LST NRCELLHOEUTRANMEAGRP:INTERRHOTOEUTRANMEASGRPID=2',
#                      'LST NRDUCELLSRSMEAS']
