# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'huaweistartup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(487, 397)
        mainWindow.setMaximumSize(QtCore.QSize(677, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/icons/chinamobile.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setIconSize(QtCore.QSize(100, 50))
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-10, 100, 451, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(1, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.load_5g_common_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_5g_common_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_5g_common_btn.setObjectName("load_5g_common_btn")
        self.gridLayout.addWidget(self.load_5g_common_btn, 0, 0, 1, 1)
        self.load_raw_data_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_raw_data_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_raw_data_btn.setObjectName("load_raw_data_btn")
        self.gridLayout.addWidget(self.load_raw_data_btn, 4, 0, 1, 1)
        self.load_4g_site_info_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_4g_site_info_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_4g_site_info_prgbar.setProperty("value", 0)
        self.load_4g_site_info_prgbar.setObjectName("load_4g_site_info_prgbar")
        self.gridLayout.addWidget(self.load_4g_site_info_prgbar, 3, 3, 1, 1)
        self.load_5g_common_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_5g_common_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_5g_common_prgbar.setProperty("value", 0)
        self.load_5g_common_prgbar.setObjectName("load_5g_common_prgbar")
        self.gridLayout.addWidget(self.load_5g_common_prgbar, 0, 3, 1, 1)
        self.load_5g_site_info_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_5g_site_info_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_5g_site_info_btn.setObjectName("load_5g_site_info_btn")
        self.gridLayout.addWidget(self.load_5g_site_info_btn, 2, 0, 1, 1)
        self.load_4g_site_info_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_4g_site_info_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_4g_site_info_btn.setObjectName("load_4g_site_info_btn")
        self.gridLayout.addWidget(self.load_4g_site_info_btn, 3, 0, 1, 1)
        self.load_5g_site_info_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_5g_site_info_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_5g_site_info_prgbar.setProperty("value", 0)
        self.load_5g_site_info_prgbar.setObjectName("load_5g_site_info_prgbar")
        self.gridLayout.addWidget(self.load_5g_site_info_prgbar, 2, 3, 1, 1)
        self.start_4g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_4g_site_info_btn.setEnabled(False)
        self.start_4g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_4g_site_info_btn.setFont(font)
        self.start_4g_site_info_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_4g_site_info_btn.setObjectName("start_4g_site_info_btn")
        self.gridLayout.addWidget(self.start_4g_site_info_btn, 3, 2, 1, 1)
        self.start_5g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_5g_common_btn.setEnabled(False)
        self.start_5g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_5g_common_btn.setFont(font)
        self.start_5g_common_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_5g_common_btn.setObjectName("start_5g_common_btn")
        self.gridLayout.addWidget(self.start_5g_common_btn, 0, 2, 1, 1)
        self.start_5g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_5g_site_info_btn.setEnabled(False)
        self.start_5g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_5g_site_info_btn.setFont(font)
        self.start_5g_site_info_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_5g_site_info_btn.setObjectName("start_5g_site_info_btn")
        self.gridLayout.addWidget(self.start_5g_site_info_btn, 2, 2, 1, 1)
        self.load_4g_common_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_4g_common_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_4g_common_prgbar.setProperty("value", 0)
        self.load_4g_common_prgbar.setObjectName("load_4g_common_prgbar")
        self.gridLayout.addWidget(self.load_4g_common_prgbar, 1, 3, 1, 1)
        self.load_raw_data_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_raw_data_msg.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_raw_data_msg.setObjectName("load_raw_data_msg")
        self.gridLayout.addWidget(self.load_raw_data_msg, 4, 4, 1, 1)
        self.load_5g_site_info_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_5g_site_info_msg.setObjectName("load_5g_site_info_msg")
        self.gridLayout.addWidget(self.load_5g_site_info_msg, 2, 4, 1, 1)
        self.start_4g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_4g_common_btn.setEnabled(False)
        self.start_4g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_4g_common_btn.setFont(font)
        self.start_4g_common_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_4g_common_btn.setObjectName("start_4g_common_btn")
        self.gridLayout.addWidget(self.start_4g_common_btn, 1, 2, 1, 1)
        self.load_5g_common_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.load_5g_common_msg.setFont(font)
        self.load_5g_common_msg.setObjectName("load_5g_common_msg")
        self.gridLayout.addWidget(self.load_5g_common_msg, 0, 4, 1, 1)
        self.load_raw_data_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_raw_data_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_raw_data_prgbar.setProperty("value", 0)
        self.load_raw_data_prgbar.setObjectName("load_raw_data_prgbar")
        self.gridLayout.addWidget(self.load_raw_data_prgbar, 4, 3, 1, 1)
        self.load_4g_common_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_4g_common_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_4g_common_btn.setObjectName("load_4g_common_btn")
        self.gridLayout.addWidget(self.load_4g_common_btn, 1, 0, 1, 1)
        self.start_raw_data_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_raw_data_btn.setEnabled(False)
        self.start_raw_data_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.start_raw_data_btn.setFont(font)
        self.start_raw_data_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_raw_data_btn.setObjectName("start_raw_data_btn")
        self.gridLayout.addWidget(self.start_raw_data_btn, 4, 2, 1, 1)
        self.load_4g_site_info_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_4g_site_info_msg.setObjectName("load_4g_site_info_msg")
        self.gridLayout.addWidget(self.load_4g_site_info_msg, 3, 4, 1, 1)
        self.load_4g_common_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_4g_common_msg.setObjectName("load_4g_common_msg")
        self.gridLayout.addWidget(self.load_4g_common_msg, 1, 4, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.huawei_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.huawei_radio.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../.designer/icons/华为1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.huawei_radio.setIcon(icon1)
        self.huawei_radio.setChecked(True)
        self.huawei_radio.setObjectName("huawei_radio")
        self.horizontalLayout.addWidget(self.huawei_radio)
        self.zte_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.zte_radio.setEnabled(True)
        self.zte_radio.setMouseTracking(True)
        self.zte_radio.setAcceptDrops(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../.designer/icons/ZTE大.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zte_radio.setIcon(icon2)
        self.zte_radio.setCheckable(True)
        self.zte_radio.setChecked(False)
        self.zte_radio.setObjectName("zte_radio")
        self.horizontalLayout.addWidget(self.zte_radio)
        self.eri_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../.designer/icons/ericsson.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eri_radio.setIcon(icon3)
        self.eri_radio.setObjectName("eri_radio")
        self.horizontalLayout.addWidget(self.eri_radio)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 230, 191, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.check_btn.setFont(font)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout_2.addWidget(self.check_btn)
        self.check_prgbar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.check_prgbar.setProperty("value", 0)
        self.check_prgbar.setObjectName("check_prgbar")
        self.horizontalLayout_2.addWidget(self.check_prgbar)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 251, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.g4_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.g4_radio.setFont(font)
        self.g4_radio.setIcon(icon1)
        self.g4_radio.setObjectName("g4_radio")
        self.horizontalLayout_3.addWidget(self.g4_radio)
        self.g5_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.g5_radio.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.g5_radio.setFont(font)
        self.g5_radio.setMouseTracking(True)
        self.g5_radio.setAcceptDrops(False)
        self.g5_radio.setIcon(icon2)
        self.g5_radio.setCheckable(True)
        self.g5_radio.setChecked(True)
        self.g5_radio.setObjectName("g5_radio")
        self.horizontalLayout_3.addWidget(self.g5_radio)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 420, 24))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.huawei_command_btn = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.huawei_command_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.huawei_command_btn.setObjectName("huawei_command_btn")
        self.gridLayout_2.addWidget(self.huawei_command_btn, 0, 2, 1, 1)
        self.load_check_rule_btn = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.load_check_rule_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.load_check_rule_btn.setObjectName("load_check_rule_btn")
        self.gridLayout_2.addWidget(self.load_check_rule_btn, 0, 0, 1, 1)
        self.set_work_dir_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.set_work_dir_label.setText("")
        self.set_work_dir_label.setObjectName("set_work_dir_label")
        self.gridLayout_2.addWidget(self.set_work_dir_label, 0, 5, 1, 1)
        self.set_work_dir_btn = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.set_work_dir_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.set_work_dir_btn.setObjectName("set_work_dir_btn")
        self.gridLayout_2.addWidget(self.set_work_dir_btn, 0, 4, 1, 1)
        self.load_check_rule_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.load_check_rule_label.setText("")
        self.load_check_rule_label.setObjectName("load_check_rule_label")
        self.gridLayout_2.addWidget(self.load_check_rule_label, 0, 1, 1, 1)
        self.huaweicommand_btn_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.huaweicommand_btn_label.setText("")
        self.huaweicommand_btn_label.setObjectName("huaweicommand_btn_label")
        self.gridLayout_2.addWidget(self.huaweicommand_btn_label, 0, 3, 1, 1)
        self.loggerText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.loggerText.setGeometry(QtCore.QRect(10, 270, 421, 101))
        self.loggerText.setObjectName("loggerText")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "@爱立信@华为@中兴互操作参数核查"))
        self.load_5g_common_btn.setText(_translate("mainWindow", "导入5G工参表"))
        self.load_raw_data_btn.setText(_translate("mainWindow", "解析网管原始数据"))
        self.load_5g_site_info_btn.setText(_translate("mainWindow", "导入5G物理站信息表"))
        self.load_4g_site_info_btn.setText(_translate("mainWindow", "导入4G物理站信息表"))
        self.start_4g_site_info_btn.setText(_translate("mainWindow", "加载"))
        self.start_5g_common_btn.setText(_translate("mainWindow", "加载"))
        self.start_5g_site_info_btn.setText(_translate("mainWindow", "加载"))
        self.load_raw_data_msg.setText(_translate("mainWindow", "未开始"))
        self.load_5g_site_info_msg.setText(_translate("mainWindow", "未导入"))
        self.start_4g_common_btn.setText(_translate("mainWindow", "加载"))
        self.load_5g_common_msg.setText(_translate("mainWindow", "未导入"))
        self.load_4g_common_btn.setText(_translate("mainWindow", "导入4G工参表"))
        self.start_raw_data_btn.setText(_translate("mainWindow", "解析"))
        self.load_4g_site_info_msg.setText(_translate("mainWindow", "未导入"))
        self.load_4g_common_msg.setText(_translate("mainWindow", "未导入"))
        self.huawei_radio.setText(_translate("mainWindow", "华为"))
        self.zte_radio.setText(_translate("mainWindow", "中兴"))
        self.eri_radio.setText(_translate("mainWindow", "爱立信"))
        self.check_btn.setText(_translate("mainWindow", "核   查"))
        self.g4_radio.setText(_translate("mainWindow", "4G"))
        self.g5_radio.setText(_translate("mainWindow", "5G"))
        self.huawei_command_btn.setText(_translate("mainWindow", "华为命令集"))
        self.load_check_rule_btn.setText(_translate("mainWindow", "规则引擎表"))
        self.set_work_dir_btn.setText(_translate("mainWindow", "工作目录"))

    def getLoggerText(self):
        return self.loggerText