# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'huaweistartup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 356)
        MainWindow.setMaximumSize(QtCore.QSize(677, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/icons/chinamobile.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(100, 50))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 381, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.load_4g_site_info_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_4g_site_info_btn.setObjectName("load_4g_site_info_btn")
        self.gridLayout.addWidget(self.load_4g_site_info_btn, 3, 0, 1, 1)
        self.start_4g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_4g_common_btn.setEnabled(False)
        self.start_4g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setKerning(True)
        self.start_4g_common_btn.setFont(font)
        self.start_4g_common_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_4g_common_btn.setObjectName("start_4g_common_btn")
        self.gridLayout.addWidget(self.start_4g_common_btn, 1, 2, 1, 1)
        self.load_check_rule_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_check_rule_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_check_rule_prgbar.setProperty("value", 0)
        self.load_check_rule_prgbar.setObjectName("load_check_rule_prgbar")
        self.gridLayout.addWidget(self.load_check_rule_prgbar, 4, 4, 1, 1)
        self.load_raw_data_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_raw_data_msg.setMaximumSize(QtCore.QSize(30, 16777215))
        self.load_raw_data_msg.setObjectName("load_raw_data_msg")
        self.gridLayout.addWidget(self.load_raw_data_msg, 6, 5, 1, 1)
        self.load_4g_common_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_4g_common_btn.setObjectName("load_4g_common_btn")
        self.gridLayout.addWidget(self.load_4g_common_btn, 1, 0, 1, 1)
        self.stop_raw_data_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_raw_data_btn.setEnabled(False)
        self.stop_raw_data_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.stop_raw_data_btn.setFont(font)
        self.stop_raw_data_btn.setStyleSheet("background-color: rgb(229, 59, 7);")
        self.stop_raw_data_btn.setObjectName("stop_raw_data_btn")
        self.gridLayout.addWidget(self.stop_raw_data_btn, 6, 3, 1, 1)
        self.load_raw_data_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_raw_data_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_raw_data_prgbar.setProperty("value", 0)
        self.load_raw_data_prgbar.setObjectName("load_raw_data_prgbar")
        self.gridLayout.addWidget(self.load_raw_data_prgbar, 6, 4, 1, 1)
        self.start_5g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_5g_site_info_btn.setEnabled(False)
        self.start_5g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setKerning(True)
        self.start_5g_site_info_btn.setFont(font)
        self.start_5g_site_info_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_5g_site_info_btn.setObjectName("start_5g_site_info_btn")
        self.gridLayout.addWidget(self.start_5g_site_info_btn, 2, 2, 1, 1)
        self.load_4g_site_info_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_4g_site_info_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_4g_site_info_prgbar.setProperty("value", 0)
        self.load_4g_site_info_prgbar.setObjectName("load_4g_site_info_prgbar")
        self.gridLayout.addWidget(self.load_4g_site_info_prgbar, 3, 4, 1, 1)
        self.load_5g_common_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_5g_common_msg.setObjectName("load_5g_common_msg")
        self.gridLayout.addWidget(self.load_5g_common_msg, 0, 5, 1, 1)
        self.start_4g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_4g_site_info_btn.setEnabled(False)
        self.start_4g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setKerning(True)
        self.start_4g_site_info_btn.setFont(font)
        self.start_4g_site_info_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_4g_site_info_btn.setObjectName("start_4g_site_info_btn")
        self.gridLayout.addWidget(self.start_4g_site_info_btn, 3, 2, 1, 1)
        self.load_5g_site_info_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_5g_site_info_msg.setObjectName("load_5g_site_info_msg")
        self.gridLayout.addWidget(self.load_5g_site_info_msg, 2, 5, 1, 1)
        self.load_5g_common_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_5g_common_btn.setObjectName("load_5g_common_btn")
        self.gridLayout.addWidget(self.load_5g_common_btn, 0, 0, 1, 1)
        self.load_5g_common_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_5g_common_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_5g_common_prgbar.setProperty("value", 0)
        self.load_5g_common_prgbar.setObjectName("load_5g_common_prgbar")
        self.gridLayout.addWidget(self.load_5g_common_prgbar, 0, 4, 1, 1)
        self.out_put_dir_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.out_put_dir_btn.setObjectName("out_put_dir_btn")
        self.gridLayout.addWidget(self.out_put_dir_btn, 5, 0, 1, 1)
        self.stop_4g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_4g_common_btn.setEnabled(False)
        self.stop_4g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.stop_4g_common_btn.setFont(font)
        self.stop_4g_common_btn.setStyleSheet("background-color: rgb(229, 59, 7);")
        self.stop_4g_common_btn.setObjectName("stop_4g_common_btn")
        self.gridLayout.addWidget(self.stop_4g_common_btn, 1, 3, 1, 1)
        self.load_raw_data_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_raw_data_btn.setObjectName("load_raw_data_btn")
        self.gridLayout.addWidget(self.load_raw_data_btn, 6, 0, 1, 1)
        self.load_4g_site_info_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_4g_site_info_msg.setObjectName("load_4g_site_info_msg")
        self.gridLayout.addWidget(self.load_4g_site_info_msg, 3, 5, 1, 1)
        self.out_put_dir_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.out_put_dir_msg.setObjectName("out_put_dir_msg")
        self.gridLayout.addWidget(self.out_put_dir_msg, 5, 5, 1, 1)
        self.load_5g_site_info_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_5g_site_info_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_5g_site_info_prgbar.setProperty("value", 0)
        self.load_5g_site_info_prgbar.setObjectName("load_5g_site_info_prgbar")
        self.gridLayout.addWidget(self.load_5g_site_info_prgbar, 2, 4, 1, 1)
        self.start_raw_data_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_raw_data_btn.setEnabled(False)
        self.start_raw_data_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setKerning(True)
        self.start_raw_data_btn.setFont(font)
        self.start_raw_data_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_raw_data_btn.setObjectName("start_raw_data_btn")
        self.gridLayout.addWidget(self.start_raw_data_btn, 6, 2, 1, 1)
        self.stop_4g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_4g_site_info_btn.setEnabled(False)
        self.stop_4g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.stop_4g_site_info_btn.setFont(font)
        self.stop_4g_site_info_btn.setStyleSheet("background-color: rgb(229, 59, 7);")
        self.stop_4g_site_info_btn.setObjectName("stop_4g_site_info_btn")
        self.gridLayout.addWidget(self.stop_4g_site_info_btn, 3, 3, 1, 1)
        self.load_5g_site_info_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_5g_site_info_btn.setObjectName("load_5g_site_info_btn")
        self.gridLayout.addWidget(self.load_5g_site_info_btn, 2, 0, 1, 1)
        self.load_check_rule_btn = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_check_rule_btn.setObjectName("load_check_rule_btn")
        self.gridLayout.addWidget(self.load_check_rule_btn, 4, 0, 1, 1)
        self.load_4g_common_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_4g_common_msg.setObjectName("load_4g_common_msg")
        self.gridLayout.addWidget(self.load_4g_common_msg, 1, 5, 1, 1)
        self.stop_5g_site_info_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_5g_site_info_btn.setEnabled(False)
        self.stop_5g_site_info_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.stop_5g_site_info_btn.setFont(font)
        self.stop_5g_site_info_btn.setStyleSheet("background-color: rgb(229, 59, 7);")
        self.stop_5g_site_info_btn.setObjectName("stop_5g_site_info_btn")
        self.gridLayout.addWidget(self.stop_5g_site_info_btn, 2, 3, 1, 1)
        self.load_check_rule_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.load_check_rule_msg.setObjectName("load_check_rule_msg")
        self.gridLayout.addWidget(self.load_check_rule_msg, 4, 5, 1, 1)
        self.stop_5g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_5g_common_btn.setEnabled(False)
        self.stop_5g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.stop_5g_common_btn.setFont(font)
        self.stop_5g_common_btn.setStyleSheet("background-color: rgb(229, 59, 7);")
        self.stop_5g_common_btn.setObjectName("stop_5g_common_btn")
        self.gridLayout.addWidget(self.stop_5g_common_btn, 0, 3, 1, 1)
        self.load_4g_common_prgbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.load_4g_common_prgbar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.load_4g_common_prgbar.setProperty("value", 0)
        self.load_4g_common_prgbar.setObjectName("load_4g_common_prgbar")
        self.gridLayout.addWidget(self.load_4g_common_prgbar, 1, 4, 1, 1)
        self.start_5g_common_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_5g_common_btn.setEnabled(False)
        self.start_5g_common_btn.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setPointSize(7)
        font.setKerning(True)
        self.start_5g_common_btn.setFont(font)
        self.start_5g_common_btn.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.start_5g_common_btn.setObjectName("start_5g_common_btn")
        self.gridLayout.addWidget(self.start_5g_common_btn, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 240, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.huawei_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.huawei_radio.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/icons/华为1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.huawei_radio.setIcon(icon1)
        self.huawei_radio.setObjectName("huawei_radio")
        self.horizontalLayout.addWidget(self.huawei_radio)
        self.zte_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.zte_radio.setEnabled(True)
        self.zte_radio.setMouseTracking(True)
        self.zte_radio.setAcceptDrops(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../.designer/icons/ZTE大.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zte_radio.setIcon(icon2)
        self.zte_radio.setCheckable(True)
        self.zte_radio.setChecked(True)
        self.zte_radio.setObjectName("zte_radio")
        self.horizontalLayout.addWidget(self.zte_radio)
        self.eri_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../.designer/icons/ericsson.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eri_radio.setIcon(icon3)
        self.eri_radio.setObjectName("eri_radio")
        self.horizontalLayout.addWidget(self.eri_radio)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 271, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("爱奇艺黑体")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.check_btn.setFont(font)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout_2.addWidget(self.check_btn)
        self.check_prgbar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.check_prgbar.setProperty("value", 0)
        self.check_prgbar.setObjectName("check_prgbar")
        self.horizontalLayout_2.addWidget(self.check_prgbar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_4g_site_info_btn.setText(_translate("MainWindow", "加载4G物理站信息表"))
        self.start_4g_common_btn.setText(_translate("MainWindow", "加载"))
        self.load_raw_data_msg.setText(_translate("MainWindow", "成功"))
        self.load_4g_common_btn.setText(_translate("MainWindow", "加载4G工参表"))
        self.stop_raw_data_btn.setText(_translate("MainWindow", "停止"))
        self.start_5g_site_info_btn.setText(_translate("MainWindow", "加载"))
        self.load_5g_common_msg.setText(_translate("MainWindow", "成功"))
        self.start_4g_site_info_btn.setText(_translate("MainWindow", "加载"))
        self.load_5g_site_info_msg.setText(_translate("MainWindow", "成功"))
        self.load_5g_common_btn.setText(_translate("MainWindow", "加载5G工参表"))
        self.out_put_dir_btn.setText(_translate("MainWindow", "结果输出文件夹"))
        self.stop_4g_common_btn.setText(_translate("MainWindow", "停止"))
        self.load_raw_data_btn.setText(_translate("MainWindow", "导入网管原始数据"))
        self.load_4g_site_info_msg.setText(_translate("MainWindow", "成功"))
        self.out_put_dir_msg.setText(_translate("MainWindow", "成功"))
        self.start_raw_data_btn.setText(_translate("MainWindow", "解析"))
        self.stop_4g_site_info_btn.setText(_translate("MainWindow", "停止"))
        self.load_5g_site_info_btn.setText(_translate("MainWindow", "加载5G物理站信息表"))
        self.load_check_rule_btn.setText(_translate("MainWindow", "加载核查规则配置表"))
        self.load_4g_common_msg.setText(_translate("MainWindow", "成功"))
        self.stop_5g_site_info_btn.setText(_translate("MainWindow", "停止"))
        self.load_check_rule_msg.setText(_translate("MainWindow", "成功"))
        self.stop_5g_common_btn.setText(_translate("MainWindow", "停止"))
        self.start_5g_common_btn.setText(_translate("MainWindow", "加载"))
        self.huawei_radio.setText(_translate("MainWindow", "华为"))
        self.zte_radio.setText(_translate("MainWindow", "中兴"))
        self.eri_radio.setText(_translate("MainWindow", "爱立信"))
        self.check_btn.setText(_translate("MainWindow", "核   查"))

